name: senti
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # It is good practice to separate icons if you have many, 
    # but putting them in images is fine too.
    - assets/icons/

  fonts:
    - family: CanvaSans
      fonts:
        - asset: assets/fonts/canva-sans-regular-italic.otf
          style: italic
